version: '3'

services:
  bot-video-downloader:
    build: .
    container_name: bot-video-downloader
    restart: always
    environment:
      TZ: America/Cuiaba
      PATH_BROWSER: ${PATH_BROWSER}
      SHIPPING_ALLOWED: ${SHIPPING_ALLOWED}
      STRING_TO_GROUP_WWEBJS: ${STRING_TO_GROUP_WWEBJS}
    volumes:
      - ./auth:/auth