version: "3"

services:
  bot-video-downloader:
    build: .
    container_name: bot-video-downloader
    restart: always
    env_file: .env
    environment:
      TZ: America/Cuiaba
    volumes:
      - ./auth:/app/auth
      - ./data:/app/data
